apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3  # Multiple replicas for web server
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pdf-chatbot-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password123@mongodb-service:27017/"
        - name: SECRET_KEY
          value: "your_secret_key_here"
        - name: ALGORITHM
          value: "HS256"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"
        - name: GROQ_API_KEY
          value: "your_groq_api_key_here"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 